/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.*;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.*;

/**
 *
 * @author quanganh
 */
public class FormSach extends javax.swing.JFrame {

    /**
     * Creates new form FormSach
     */
    private void LoadData() {
        try {
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Mã sách");
            model.addColumn("Tên sách");
            model.addColumn("Số lượng kho");
            model.addColumn("Giá bán");
            model.addColumn("Mã tác giả");
            model.addColumn("Mã danh mục");

            List<Sach> ds = SachDAO.getAllBooks();

            for (Sach s : ds) {
                Object[] row = {
                    s.getMaSach(),
                    s.getTenSach(),
                    s.getSlKho(),
                    s.getGiaBan(),
                    s.getMaTG(),
                    s.getMaDanhMuc()
                };
                model.addRow(row);
            }

            // Set model cho jTable1
            jTable1.setModel(model);
        } catch (Exception ex) {
            ex.printStackTrace();
            // Xử lý lỗi nếu cần
        }
        txt_maSach.setText("");
        txt_tenSach.setText("");
        txt_giaBan.setText("");
        txt_sl.setText("");
        txt_maSach.enable(true);
        this.setTitle("Sách");
        List<DanhMucSach> dm = DanhMucSachDAO.getAllCategories();
        DefaultComboBoxModel<DanhMucSach> spModel = new DefaultComboBoxModel<>(dm.toArray(new DanhMucSach[0]));
        cbx_maDanhMuc.setModel(spModel);

        List<TacGia> tg = SachDAO.getAllTacGia();
        DefaultComboBoxModel<TacGia> spModel2 = new DefaultComboBoxModel<>(tg.toArray(new TacGia[0]));
        cbx_maTacGia.setModel(spModel2);
    }

    private String getMaDanhMuc() {
        DanhMucSach selected = (DanhMucSach) cbx_maDanhMuc.getSelectedItem();
        if (selected != null) {
            return selected.getMaDanhMuc(); // Thay "getId()" bằng phương thức bạn sử dụng để lấy ID của Phim
        }
        return null; // hoặc giá trị mặc định tùy thuộc vào yêu cầu của bạn
    }

    private String getMaTacGia() {
        TacGia selected = (TacGia) cbx_maTacGia.getSelectedItem();
        if (selected != null) {
            return selected.getMaTG(); // Thay "getId()" bằng phương thức bạn sử dụng để lấy ID của Phim
        }
        return null; // hoặc giá trị mặc định tùy thuộc vào yêu cầu của bạn
    }

    public FormSach() {
        initComponents();
        LoadData();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_maSach = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbx_maTacGia = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbx_maDanhMuc = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txt_giaBan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_sl = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_tenSach = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã sách");

        jLabel2.setText("Tên tác giả");

        jLabel3.setText("Tên danh mục");

        jLabel4.setText("Giá bán");

        jLabel5.setText("Số lượng kho");

        jLabel6.setText("Tên sách");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Làm mới");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Tìm kiếm theo tên sách");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnMenu)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(48, 48, 48)
                                            .addComponent(txt_maSach, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(33, 33, 33)
                                                .addComponent(cbx_maTacGia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(18, 18, 18)
                                                .addComponent(cbx_maDanhMuc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGap(84, 84, 84)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel4))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txt_sl, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txt_giaBan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txt_tenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 185, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_maSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt_giaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbx_maTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txt_sl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbx_maDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_tenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txt_maSach.setEnabled(true);
        // Kiểm tra trường trống
        if (txt_maSach.getText().isEmpty() || txt_tenSach.getText().isEmpty()
                || txt_giaBan.getText().isEmpty() || txt_sl.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đầy đủ thông tin.");
            return; // Dừng thực hiện nếu có trường trống
        }

        // Kiểm tra trùng khóa
        if (SachDAO.isBookExists(txt_maSach.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Mã sách đã tồn tại.");
            return; // Dừng thực hiện nếu mã sách đã tồn tại
        }
        Sach newObj = new Sach(txt_maSach.getText(), getMaTacGia(),
                getMaDanhMuc(), Double.parseDouble(txt_giaBan.getText()), Integer.parseInt(txt_sl.getText()),
                txt_tenSach.getText());
        if (SachDAO.addBook(newObj)) {
            JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
            LoadData();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Thêm thất bại");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txt_maSach.setEnabled(false);
        Sach newObj = new Sach(txt_maSach.getText(), getMaTacGia(),
                getMaDanhMuc(), Double.parseDouble(txt_giaBan.getText()), Integer.parseInt(txt_sl.getText()),
                txt_tenSach.getText());
        if (SachDAO.updateBook(newObj)) {
            JOptionPane.showMessageDialog(rootPane, "Sửa thành công");
            LoadData();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Sửa thất bại");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (SachDAO.deleteBook(txt_maSach.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Xóa thành công");
            LoadData();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Xóa thất bại");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        LoadData();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        txt_maSach.setEnabled(true);
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            String maSach = (String) jTable1.getValueAt(selectedRow, 0);
            String tenSach = (String) jTable1.getValueAt(selectedRow, 1);
            Integer sl = (Integer) jTable1.getValueAt(selectedRow, 2);
            Double giaBan = (Double) jTable1.getValueAt(selectedRow, 3);

            txt_maSach.setText(maSach);
            txt_maSach.enable(false);
            txt_tenSach.setText(tenSach);
            txt_sl.setText(sl.toString());
            txt_giaBan.setText(giaBan.toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Mã sách");
            model.addColumn("Tên sách");
            model.addColumn("Số lượng kho");
            model.addColumn("Giá bán");
            model.addColumn("Mã tác giả");
            model.addColumn("Mã danh mục");

            List<Sach> ds = SachDAO.findBooksByName(txt_tenSach.getText());

            for (Sach s : ds) {
                Object[] row = {
                    s.getMaSach(),
                    s.getTenSach(),
                    s.getSlKho(),
                    s.getGiaBan(),
                    s.getMaTG(),
                    s.getMaDanhMuc()
                };
                model.addRow(row);
            }

            // Set model cho jTable1
            jTable1.setModel(model);
        } catch (Exception ex) {
            ex.printStackTrace();
            // Xử lý lỗi nếu cần
        }
        txt_maSach.setText("");
        txt_tenSach.setText("");
        txt_giaBan.setText("");
        txt_sl.setText("");
        txt_maSach.enable(true);
        List<DanhMucSach> dm = DanhMucSachDAO.getAllCategories();
        DefaultComboBoxModel<DanhMucSach> spModel = new DefaultComboBoxModel<>(dm.toArray(new DanhMucSach[0]));
        cbx_maDanhMuc.setModel(spModel);

        List<TacGia> tg = SachDAO.getAllTacGia();
        DefaultComboBoxModel<TacGia> spModel2 = new DefaultComboBoxModel<>(tg.toArray(new TacGia[0]));
        cbx_maTacGia.setModel(spModel2);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        new frmMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu;
    private javax.swing.JComboBox<DanhMucSach> cbx_maDanhMuc;
    private javax.swing.JComboBox<TacGia> cbx_maTacGia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_giaBan;
    private javax.swing.JTextField txt_maSach;
    private javax.swing.JTextField txt_sl;
    private javax.swing.JTextField txt_tenSach;
    // End of variables declaration//GEN-END:variables
}
