/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.ChiTietPhieuDAO;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.ChiTietPhieuNhap;

/**
 *
 * @author Admin
 */
public class frmCTPN extends javax.swing.JFrame {

    DefaultTableModel dtm = new DefaultTableModel();
    ArrayList<ChiTietPhieuNhap> dsCT = ChiTietPhieuDAO.layDSCTPN();

    /**
     * Creates new form frmCTPN
     */
    public frmCTPN() {
        initComponents();

        this.setLocationRelativeTo(null);
        this.setTitle("Chi tiết phiếu nhập");
        String[] tieuDe = {"Mã phiếu", "Tên sách", "Số lượng", "Giá nhập"};
        dtm.setColumnIdentifiers(tieuDe);

        hienThi(dsCT);
        cboMaPhieu.enable(false);
        cboTenSach.enable(false);
        txtSoLuong.enable(false);
        txtGiaNhap.enable(false);

        ArrayList<String> dsPhieu = ChiTietPhieuDAO.getDataForCBOMaPhieu();
        for (String s : dsPhieu) {
            cboMaPhieu.addItem(s);
        }

        ArrayList<String> dsSach = ChiTietPhieuDAO.getDataForCBOSach();
        for (String s : dsSach) {
            cboTenSach.addItem(s);
        }

        tbCTPN.setModel(dtm);
    }

    public void hienThi(ArrayList<ChiTietPhieuNhap> ds) {
        dtm.setRowCount(0);
        for (ChiTietPhieuNhap ct : ds) {
            Vector<Object> vec = new Vector<Object>();
            vec.add(ct.getMaPhieu());
            String tenSach = ChiTietPhieuDAO.layTenSach(ct.getMaSach().toString());
            vec.add(tenSach);
            vec.add(ct.getSoLuong());
            vec.add(ct.getGiaNhap());

            dtm.addRow(vec);
        }
    }

    public boolean ktNhap(int x) { // x == 1 là tìm kiếm
        boolean kq = true;
        if (x != 1) {
            if (txtSoLuong.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Số lượng không được bỏ trống. Vui lòng nhập lại");
                kq = false;
            } else if (txtSoLuong.getText().toString().matches(".*\\D.*")) {
                kq = false;
                JOptionPane.showMessageDialog(this, "Số lượng không được có chữ. Vui lòng nhập lại!");
                txtSoLuong.requestFocus();
            } else if (Integer.parseInt(txtSoLuong.getText().toString()) <= 0) {
                JOptionPane.showMessageDialog(this, "Số lượng không được nhỏ hơn hoặc bằng 0. Vui lòng nhập lại");
                kq = false;
            } else if (txtGiaNhap.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Giá nhập không được bỏ trống. Vui lòng nhập lại");
                kq = false;
            } else if (txtGiaNhap.getText().toString().contains(",")) {
                JOptionPane.showMessageDialog(this, "Hãy sử dụng dấu (.) thay vì (,). Vui lòng nhập lại");
                kq = false;
            } else if (Float.parseFloat(txtGiaNhap.getText().toString()) <= 0) {
                JOptionPane.showMessageDialog(this, "Giá nhập không được nhỏ hơn hoặc bằng 0. Vui lòng nhập lại");
                kq = false;
            }
        }

        return kq;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCTPN = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        cboMaPhieu = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cboTenSach = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGiaNhap = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("CHI TIẾT PHIẾU NHẬP");

        tbCTPN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbCTPN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCTPNMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbCTPN);

        jLabel3.setText("Mã phiếu");

        jLabel4.setText("Tên sách");

        jLabel5.setText("Số lượng");

        jLabel6.setText("Giá nhập");

        btnInsert.setText("Thêm");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnUpdate.setText("Sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSearch.setText("Tìm kiếm theo mã phiếu");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnBack.setText("Trở về phiếu nhập");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(404, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(165, 165, 165)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtGiaNhap)
                            .addComponent(cboMaPhieu, 0, 145, Short.MAX_VALUE))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(btnSave)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSoLuong)
                            .addComponent(cboTenSach, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInsert, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cboMaPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInsert)
                            .addComponent(jLabel4)
                            .addComponent(cboTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdate)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(btnSave)
                    .addComponent(btnDelete))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        frmPhieuNhap frmPN = new frmPhieuNhap();
        frmPN.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void tbCTPNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCTPNMouseClicked
        // TODO add your handling code here:
        int row = tbCTPN.getSelectedRow();
        cboMaPhieu.setSelectedItem(String.valueOf(tbCTPN.getValueAt(row, 0)));
        cboTenSach.setSelectedItem(String.valueOf(tbCTPN.getValueAt(row, 1)));
        txtSoLuong.setText(String.valueOf(tbCTPN.getValueAt(row, 2)));
        txtGiaNhap.setText(String.valueOf(tbCTPN.getValueAt(row, 3)));

        cboMaPhieu.enable(false);
        cboTenSach.enable(false);
        txtSoLuong.enable(false);
        txtGiaNhap.enable(false);
    }//GEN-LAST:event_tbCTPNMouseClicked

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        cboMaPhieu.enable(true);
        cboTenSach.enable(true);
        txtSoLuong.enable(true);
        txtGiaNhap.enable(true);
        txtSoLuong.setText("");
        txtGiaNhap.setText("");
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        cboMaPhieu.enable(true);
        cboTenSach.enable(true);
        txtSoLuong.enable(true);
        txtGiaNhap.enable(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        hienThi(dsCT);
        ChiTietPhieuNhap ct = new ChiTietPhieuNhap();

        ct.setMaPhieu(cboMaPhieu.getSelectedItem().toString());
        String ma = ChiTietPhieuDAO.layMaSachTuCBO(cboTenSach.getSelectedItem().toString());
        ct.setMaSach(ma);

        if (!ChiTietPhieuDAO.ktrCTPN(ct.getMaPhieu(), ct.getMaSach())) {
            if (ktNhap(0)) {
                ct.setSoLuong(Integer.parseInt(txtSoLuong.getText().toString()));
                ct.setGiaNhap(Float.parseFloat(txtGiaNhap.getText().toString()));

                if (ChiTietPhieuDAO.themCTPN(ct)) {
                    dsCT = ChiTietPhieuDAO.layDSCTPN();
                    JOptionPane.showMessageDialog(this, "Thêm chi tiết phiếu nhập thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm chi tiết phiếu nhập thất bại. Vui lòng thử lại", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } else {
            if (ktNhap(0)) {
                ct.setSoLuong(Integer.parseInt(txtSoLuong.getText().toString()));
                ct.setGiaNhap(Float.parseFloat(txtGiaNhap.getText().toString()));

                int n = JOptionPane.showConfirmDialog(this, "Bạn đã thêm cuốn sách này ở phiếu nhập này rồi nên chỉ có thể cập nhật lại số lượng hoặc giá tiền\n Chọn Yes nếu đồng ý sửa và No khi không cần", "Thông báo", JOptionPane.YES_NO_OPTION);
                if (n == JOptionPane.YES_OPTION) {
                    if (ChiTietPhieuDAO.updateCTPN(ct)) {
                        dsCT = ChiTietPhieuDAO.layDSCTPN();
                        JOptionPane.showMessageDialog(this, "Cập nhật chi tiết phiếu nhập thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Cập nhật chi tiết phiếu nhập thất bại. Vui lòng thử lại", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            }
        }

        hienThi(dsCT);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int row = tbCTPN.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn hàng cần xóa");
        } else {
            int n = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?", "Cảnh báo", JOptionPane.YES_NO_OPTION);
            if (n == JOptionPane.NO_OPTION) {
                return;
            } else {
                String maPhieu = cboMaPhieu.getSelectedItem().toString();
                String maSach = ChiTietPhieuDAO.layMaSachTuCBO(cboTenSach.getSelectedItem().toString());

                if (ChiTietPhieuDAO.deleteCTPN(maPhieu, maSach)) {
                    dsCT = ChiTietPhieuDAO.layDSCTPN();
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa thất bại. Vui lòng thử lại");
                }
                hienThi(dsCT);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        cboTenSach.setEnabled(false);
        txtSoLuong.setEnabled(false);
        txtGiaNhap.setEnabled(false);
        cboMaPhieu.setEnabled(true);

        if (ktNhap(1)) {
            String maPN = cboMaPhieu.getSelectedItem().toString();
            ArrayList<ChiTietPhieuNhap> lst = ChiTietPhieuDAO.searchMaPN(maPN);
            if (lst.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không có chi tiết phiếu nhập của phiếu nhập này!");
            } else {
                hienThi(lst);
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCTPN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCTPN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCTPN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCTPN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCTPN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboMaPhieu;
    private javax.swing.JComboBox<String> cboTenSach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbCTPN;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables
}
