/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.KhachHangDAO;
import dao.NhaCungCapDAO;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.KhachHang;
import pojo.NhaCungCap;

/**
 *
 * @author Admin
 */
public class frmNhaCungCap extends javax.swing.JFrame {

    DefaultTableModel dtm = new DefaultTableModel();
    ArrayList<NhaCungCap> dsNCC = NhaCungCapDAO.layDSNCC();

    /**
     * Creates new form frmNhaCungCap
     */
    public frmNhaCungCap() {
        initComponents();

        this.setLocationRelativeTo(null);
        this.setTitle("Nhà cung cấp");
        String[] tieuDe = {"Mã nhà cung cấp", "Tên nhà cung cấp", "Địa chỉ", "SDT", "Email"};
        dtm.setColumnIdentifiers(tieuDe);

        hienThi(dsNCC);
        txtMaNCC.enable(false);
        txtTenNCC.enable(false);
        txtDiaChiNCC.enable(false);
        txtSDTNCC.enable(false);
        txtEmailNCC.enable(false);
        tbNhaCungCap.setModel(dtm);
    }

    public void hienThi(ArrayList<NhaCungCap> ds) {
        dtm.setRowCount(0);
        for (NhaCungCap ncc : ds) {
            Vector<Object> vec = new Vector<Object>();
            vec.add(ncc.getMaNCC());
            vec.add(ncc.getTenNCC());
            vec.add(ncc.getDiaChi());
            vec.add(ncc.getSdt());
            vec.add(ncc.getEmail());
            dtm.addRow(vec);
        }
    }

    public boolean kiemTraNhap(int loai) {
        boolean kq = true;
        String sdt = txtSDTNCC.getText().toString();
        String email = txtEmailNCC.getText().toString();
        NhaCungCap ncc = NhaCungCapDAO.searchSDT(sdt);
        NhaCungCap nccE = NhaCungCapDAO.searchEmail(email);

        if (sdt.isEmpty()) {
            kq = false;
            JOptionPane.showMessageDialog(this, "Số điện thoại không được bỏ trống. Vui lòng nhập lại!");
            txtSDTNCC.requestFocus();
        } else if (sdt.matches(".*\\D.*")) {
            kq = false;
            JOptionPane.showMessageDialog(this, "Số điện thoại không được có chữ. Vui lòng nhập lại!");
            txtSDTNCC.requestFocus();
        } else if (!sdt.substring(0, 1).equals("0")) {
            kq = false;
            JOptionPane.showMessageDialog(this, "Số điện thoại không bắt đầu bằng 0. Vui lòng nhập lại!");
            txtSDTNCC.requestFocus();
        } else if (sdt.length() < 10) {
            kq = false;
            JOptionPane.showMessageDialog(this, "Số điện thoại không đủ 10 số. Vui lòng nhập lại!");
            txtSDTNCC.requestFocus();
        } else if (sdt.length() > 11) {
            kq = false;
            JOptionPane.showMessageDialog(this, "Số điện thoại hơn 11 số. Vui lòng nhập lại!");
            txtSDTNCC.requestFocus();
        } else if (ncc.getMaNCC() != null && txtMaNCC.getText().toString().isEmpty() && loai == 0) {// loại = 0 là không phải tìm kiếm
            kq = false;
            JOptionPane.showMessageDialog(this, "Số điện thoại đã tồn tại. Vui lòng nhập lại!");
            txtSDTNCC.requestFocus();
        } else if (txtDiaChiNCC.getText().toString().isEmpty() && loai == 0) {
            kq = false;
            txtDiaChiNCC.setText("0");
            JOptionPane.showMessageDialog(this, "Địa chỉ không được để trống. Nếu mua tại chỗ không cần giao vui lòng nhập 0.\nVui lòng nhập lại!");
            return kq;
        } else if (nccE.getMaNCC() == null || nccE.getEmail().equals("")) {
            kq = true;
            return kq;
        } else if (!email.contains("@")) {
            kq = false;
            JOptionPane.showMessageDialog(this, "Emal phải có @. Vui lòng nhập lại!");
            txtEmailNCC.requestFocus();
        } else if (email.length() == 1) {
            kq = false;
            JOptionPane.showMessageDialog(this, "Email phải có kí tự khác ngoài @. Vui lòng nhập lại!");
            txtEmailNCC.requestFocus();
        } else if (nccE.getMaNCC() != null && txtMaNCC.getText().toString().isEmpty()) {
            kq = false;
            JOptionPane.showMessageDialog(this, "Email đã tồn tại. Vui lòng nhập lại!");
            txtEmailNCC.requestFocus();
        }

        return kq;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDiaChiNCC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSDTNCC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNhaCungCap = new javax.swing.JTable();
        txtEmailNCC = new javax.swing.JTextField();
        btnInsertNCC = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnUpdateNCC = new javax.swing.JButton();
        txtMaNCC = new javax.swing.JTextField();
        btnDeleteNCC = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnSearchNCC = new javax.swing.JButton();
        txtTenNCC = new javax.swing.JTextField();
        btnSaveNCC = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Số điện thoại");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("NHÀ CUNG CẤP");

        jLabel6.setText("Email");

        tbNhaCungCap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbNhaCungCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbNhaCungCapMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbNhaCungCap);

        btnInsertNCC.setText("Thêm");
        btnInsertNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertNCCActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã nhà cung cấp");

        btnUpdateNCC.setText("Sửa");
        btnUpdateNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateNCCActionPerformed(evt);
            }
        });

        btnDeleteNCC.setText("Xóa");
        btnDeleteNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteNCCActionPerformed(evt);
            }
        });

        jLabel3.setText("Tên nhà cung cấp");

        btnSearchNCC.setText("Tìm kiếm");
        btnSearchNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchNCCActionPerformed(evt);
            }
        });

        btnSaveNCC.setText("Lưu");
        btnSaveNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveNCCActionPerformed(evt);
            }
        });

        jLabel4.setText("Địa chỉ");

        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(341, 341, 341))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(jLabel2))
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(25, 25, 25))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(73, 73, 73)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDiaChiNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtSDTNCC, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                            .addComponent(txtEmailNCC)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSaveNCC)
                                        .addGap(68, 68, 68)
                                        .addComponent(btnSearchNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnUpdateNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnInsertNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDeleteNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 25, Short.MAX_VALUE)))
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnMenu))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtSDTNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertNCC))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateNCC)
                    .addComponent(jLabel3)
                    .addComponent(txtTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtEmailNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDiaChiNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteNCC)
                    .addComponent(btnSaveNCC)
                    .addComponent(btnSearchNCC))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbNhaCungCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNhaCungCapMouseClicked
        // TODO add your handling code here:

        int row = tbNhaCungCap.getSelectedRow();
        txtMaNCC.setText(String.valueOf(tbNhaCungCap.getValueAt(row, 0)));
        txtTenNCC.setText(String.valueOf(tbNhaCungCap.getValueAt(row, 1)));
        txtDiaChiNCC.setText(String.valueOf(tbNhaCungCap.getValueAt(row, 2)));
        txtSDTNCC.setText(String.valueOf(tbNhaCungCap.getValueAt(row, 3)));
        txtEmailNCC.setText(String.valueOf(tbNhaCungCap.getValueAt(row, 4)));

        txtTenNCC.enable(false);
        txtDiaChiNCC.enable(false);
        txtSDTNCC.enable(false);
        txtEmailNCC.enable(false);
    }//GEN-LAST:event_tbNhaCungCapMouseClicked

    private void btnInsertNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertNCCActionPerformed
        // TODO add your handling code here:
        hienThi(dsNCC);
        txtMaNCC.setText("");
        txtTenNCC.setText("");
        txtDiaChiNCC.setText("");
        txtSDTNCC.setText("");
        txtEmailNCC.setText("");
        txtTenNCC.enable(true);
        txtDiaChiNCC.enable(true);
        txtSDTNCC.enable(true);
        txtEmailNCC.enable(true);
        txtSDTNCC.requestFocus();
    }//GEN-LAST:event_btnInsertNCCActionPerformed

    private void btnUpdateNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateNCCActionPerformed
        // TODO add your handling code here:
        hienThi(dsNCC);
        txtTenNCC.enable(true);
        txtDiaChiNCC.enable(true);
        txtSDTNCC.enable(true);
        txtEmailNCC.enable(true);
        txtSDTNCC.requestFocus();
    }//GEN-LAST:event_btnUpdateNCCActionPerformed

    private void btnDeleteNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteNCCActionPerformed
        // TODO add your handling code here:

        int row = tbNhaCungCap.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn hàng cần xóa");
        } else {
            int n = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?", "Cảnh báo", JOptionPane.YES_NO_OPTION);
            if (n == JOptionPane.NO_OPTION) {
                return;
            } else {
                if (NhaCungCapDAO.deleteNCC(txtMaNCC.getText().toString())) {
                    dsNCC = NhaCungCapDAO.layDSNCC();
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa thất bại.\nNếu muốn xóa nhà cung cấp phải xóa các phiếu nhập từ nhà cung cấp đó. Vui lòng thử lại");
                }
                hienThi(dsNCC);
            }
        }
    }//GEN-LAST:event_btnDeleteNCCActionPerformed

    private void btnSearchNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchNCCActionPerformed
        // TODO add your handling code here:
        txtMaNCC.setText("");
        txtTenNCC.setText("");
        txtDiaChiNCC.setText("");
        txtEmailNCC.setText("");

        txtTenNCC.enable(false);
        txtDiaChiNCC.enable(false);
        txtEmailNCC.enable(false);
        txtSDTNCC.enable(true);
        txtSDTNCC.requestFocus();

        if (txtSDTNCC.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số điện thoại");
        else {
            if (kiemTraNhap(1)) {
                ArrayList<NhaCungCap> lst = new ArrayList<>();
                NhaCungCap ncc = NhaCungCapDAO.searchSDT(txtSDTNCC.getText().toString());
                if (ncc.getMaNCC() == null) {
                    JOptionPane.showMessageDialog(this, "Không có nhà cung cấp có số điện thoại này!");
                } else {
                    lst.add(ncc);
                    hienThi(lst);
                }
            }
        }
    }//GEN-LAST:event_btnSearchNCCActionPerformed

    private void btnSaveNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveNCCActionPerformed
        // TODO add your handling code here:
        hienThi(dsNCC);
        NhaCungCap ncc = new NhaCungCap();
        ncc.setTenNCC(txtTenNCC.getText().toString());
        ncc.setDiaChi(txtDiaChiNCC.getText().toString());
        ncc.setSdt(txtSDTNCC.getText().toString());
        ncc.setEmail(txtEmailNCC.getText().toString());

        if (txtMaNCC.getText().isEmpty()) {
            if (kiemTraNhap(0)) {
                if (NhaCungCapDAO.themNCC(ncc)) {
                    dsNCC = NhaCungCapDAO.layDSNCC();
                    JOptionPane.showMessageDialog(this, "Thêm nhà cung cấp thàng công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm nhà cung cấp thất bại. Vui lòng thử lại", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } else {
            if (kiemTraNhap(0)) {
                ncc.setMaNCC(txtMaNCC.getText().toString());
                if (NhaCungCapDAO.updateNCC(ncc)) {
                    dsNCC = NhaCungCapDAO.layDSNCC();
                    JOptionPane.showMessageDialog(this, "Cập nhật nhà cung cấp thàng công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Cập nhật nhà cung cấp thất bại. Vui lòng thử lại", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }

        hienThi(dsNCC);
    }//GEN-LAST:event_btnSaveNCCActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        new frmMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNhaCungCap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteNCC;
    private javax.swing.JButton btnInsertNCC;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnSaveNCC;
    private javax.swing.JButton btnSearchNCC;
    private javax.swing.JButton btnUpdateNCC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbNhaCungCap;
    private javax.swing.JTextField txtDiaChiNCC;
    private javax.swing.JTextField txtEmailNCC;
    private javax.swing.JTextField txtMaNCC;
    private javax.swing.JTextField txtSDTNCC;
    private javax.swing.JTextField txtTenNCC;
    // End of variables declaration//GEN-END:variables
}
