/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.KhachHangDAO;
import dao.ThongKeDAO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.plaf.basic.BasicBorders;
import javax.swing.table.DefaultTableModel;
import pojo.KhachHang;

/**
 *
 * @author Admin
 */
public class frmThongKe extends javax.swing.JFrame {

    DefaultTableModel dtm = new DefaultTableModel();
    ArrayList<String> ds = new ArrayList<>();

    /**
     * Creates new form frmThongKe
     */
    public frmThongKe() {
        initComponents();

        this.setLocationRelativeTo(null);
        this.setTitle("Thống kê");
        String[] tieuDe = {};
        dtm.setColumnIdentifiers(tieuDe);

        hienThiDoanhThu(ds);
        tbThongKe.setModel(dtm);
        
        
    }

    public void hienThiDoanhThu(ArrayList<String> ds) {
        dtm.setRowCount(0);

        for (int i = 0; i < ds.size(); i += 2) {
            Vector<Object> vec = new Vector<Object>();
            vec.add(ds.get(i));

            if (i + 1 < ds.size()) {
                vec.add(ds.get(i + 1));
            } else {
                vec.add(""); // Nếu không có phần tử thứ hai, thêm một giá trị trống vào cột thứ hai
            }

            dtm.addRow(vec);
        }
    }

    public void hienThiTKKH_S(ArrayList<String> ds) {
        dtm.setRowCount(0);

        for (String x : ds) {
            Vector<Object> vec = new Vector<Object>();
            vec.add(x);
            dtm.addRow(vec);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbThongKe = new javax.swing.JTable();
        rdMonth = new javax.swing.JRadioButton();
        rdYear = new javax.swing.JRadioButton();
        rdSach = new javax.swing.JRadioButton();
        rdKH = new javax.swing.JRadioButton();
        btnTK = new javax.swing.JButton();
        cboData = new javax.swing.JComboBox<>();
        btnMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("THỐNG KÊ");

        tbThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbThongKe);

        btnGroup.add(rdMonth);
        rdMonth.setText("Thống kê doanh thu theo tháng");
        rdMonth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdMonthMouseClicked(evt);
            }
        });
        rdMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdMonthActionPerformed(evt);
            }
        });

        btnGroup.add(rdYear);
        rdYear.setText("Thống kê doanh thu theo năm");
        rdYear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdYearMouseClicked(evt);
            }
        });
        rdYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdYearActionPerformed(evt);
            }
        });

        btnGroup.add(rdSach);
        rdSach.setText("Thống kê sách bán chạy");
        rdSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdSachActionPerformed(evt);
            }
        });

        btnGroup.add(rdKH);
        rdKH.setText("Thống kê khách hàng mua nhiều");
        rdKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdKHActionPerformed(evt);
            }
        });

        btnTK.setText("Thống kê");
        btnTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKActionPerformed(evt);
            }
        });

        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(334, 334, 334))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rdSach, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rdMonth))
                                .addGap(115, 115, 115)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnTK)
                                    .addComponent(rdYear)
                                    .addComponent(rdKH)))
                            .addComponent(cboData, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(52, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnMenu))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdSach)
                    .addComponent(rdKH))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdMonth)
                    .addComponent(rdYear))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTK)
                    .addComponent(cboData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKActionPerformed
        // TODO add your handling code here:
        var btn = btnGroup.getSelection();
        String data;
        if (cboData.getSelectedItem() == null) {
            data = "";
        } else {
            data = cboData.getSelectedItem().toString();
        }

        if (btn != null) {
            if (btn == rdMonth.getModel()) {
                ArrayList<String> ds = new ArrayList<>();
                try {
                    if (data.equals("All")) {

                        ArrayList<String> mon = ThongKeDAO.layThang();
                        for (String x : mon) {
                            Double kq = ThongKeDAO.thongKeTheoThang(Integer.parseInt(x));

                            ds.add(x);
                            ds.add(String.valueOf(kq));
                        }
                    } else {
                        Double kq = ThongKeDAO.thongKeTheoThang(Integer.parseInt(data));
                        ds.add(data);
                        ds.add(String.valueOf(kq));
                    }
                    String[] tieuDe = {"Tháng", "Doanh thu"};
                    dtm.setColumnIdentifiers(tieuDe);
                    hienThiDoanhThu(ds);
                } catch (SQLException ex) {
                    Logger.getLogger(frmThongKe.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (btn == rdYear.getModel()) {
                ArrayList<String> ds = new ArrayList<>();
                try {
                    if (data.equals("All")) {

                        ArrayList<String> yy = ThongKeDAO.layNam();
                        for (String x : yy) {
                            Double kq = ThongKeDAO.thongKeTheoNam(Integer.parseInt(x));

                            ds.add(x);
                            ds.add(String.valueOf(kq));
                        }
                    } else {
                        Double kq = ThongKeDAO.thongKeTheoNam(Integer.parseInt(data));
                        ds.add(data);
                        ds.add(String.valueOf(kq));
                    }
                    String[] tieuDe = {"Năm", "Doanh thu"};
                    dtm.setColumnIdentifiers(tieuDe);
                    hienThiDoanhThu(ds);
                } catch (SQLException ex) {
                    Logger.getLogger(frmThongKe.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (btn == rdSach.getModel()) {
                ArrayList<String> dsS = new ArrayList<>();
                try {
                    dsS = ThongKeDAO.thongKeSachBanChay();
                    String tieuDe = "Mã sách - Tên sách - Tên tác giả - Giá bán - SLKho";
                    dtm.setColumnIdentifiers(new Vector<>());
                    dtm.addColumn(tieuDe);
                    hienThiTKKH_S(dsS);
                } catch (SQLException ex) {
                    Logger.getLogger(frmThongKe.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (btn == rdKH.getModel()) {
                ArrayList<String> dsKH = new ArrayList<>();
                try {
                    dsKH = ThongKeDAO.thongKeKhachHangMuaNhieu();
                    String tieuDe = "Mã khách hàng - Tên khách hàng - SDT - Tổng tiền đã mua";
                    dtm.setColumnIdentifiers(new Vector<>());
                    dtm.addColumn(tieuDe);
                    hienThiTKKH_S(dsKH);
                } catch (SQLException ex) {
                    Logger.getLogger(frmThongKe.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

    }//GEN-LAST:event_btnTKActionPerformed

    private void rdMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdMonthActionPerformed
        // TODO add your handling code here:
        cboData.setEnabled(true);
        cboData.removeAllItems();
        ArrayList<String> data = ThongKeDAO.layThang();
        cboData.addItem("All");
        for (String x : data) {
            cboData.addItem(x);
        }
    }//GEN-LAST:event_rdMonthActionPerformed

    private void rdMonthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdMonthMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_rdMonthMouseClicked

    private void rdYearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdYearMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rdYearMouseClicked

    private void rdYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdYearActionPerformed
        // TODO add your handling code here:
        cboData.setEnabled(true);
        cboData.removeAllItems();
        cboData.addItem("All");
        ArrayList<String> data = ThongKeDAO.layNam();
        for (String x : data) {
            cboData.addItem(x);
        }
    }//GEN-LAST:event_rdYearActionPerformed

    private void rdSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdSachActionPerformed
        // TODO add your handling code here:
        cboData.setEnabled(false);
    }//GEN-LAST:event_rdSachActionPerformed

    private void rdKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdKHActionPerformed
        // TODO add your handling code here:
        cboData.setEnabled(false);
    }//GEN-LAST:event_rdKHActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        new frmMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmThongKe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnTK;
    private javax.swing.JComboBox<String> cboData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdKH;
    private javax.swing.JRadioButton rdMonth;
    private javax.swing.JRadioButton rdSach;
    private javax.swing.JRadioButton rdYear;
    private javax.swing.JTable tbThongKe;
    // End of variables declaration//GEN-END:variables
}
